package dev.flashbackfix.mixin;

import com.moulberry.flashback.playback.ReplayServer;
import io.netty.channel.ChannelHandlerContext;
import io.netty.handler.codec.EncoderException;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import net.minecraft.network.Connection;
import net.minecraft.network.PacketListener;
import net.minecraft.server.network.ServerCommonPacketListenerImpl;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * Keeps one malformed fake-server synchronization payload from destroying the replay connection.
 *
 * <p>Joining a replay fires every installed mod's normal server-join hooks against Flashback's
 * reconstructed ReplayServer. Some mods serialize global reload state which is valid on the real
 * server but incomplete in that fake server. Packet encoding happens later on Netty, outside the
 * sender's call stack, and vanilla treats any EncoderException as a fatal connection error. The bad
 * packet has already failed and been discarded by Netty at this point, so retaining the connection is
 * safe and lets recorded authoritative payloads continue to initialize the client.</p>
 */
@Mixin(Connection.class)
public abstract class MixinConnectionReplayEncoderFault {

    @Unique
    private static final Logger FLASHBACK_NEOFORGE_FIXED$LOGGER =
            LoggerFactory.getLogger("FlashbackNeoForgeFixed");
    @Unique
    private static final Set<String> FLASHBACK_NEOFORGE_FIXED$LOGGED_ENCODER_FAILURES =
            ConcurrentHashMap.newKeySet();

    @Inject(method = "exceptionCaught", at = @At("HEAD"), cancellable = true)
    private void flashbackNeoForgeFixed$keepReplayConnectedAfterBadOutboundPacket(
            ChannelHandlerContext context, Throwable exception, CallbackInfo ci) {
        if (!(exception instanceof EncoderException)) {
            return;
        }

        PacketListener listener = ((Connection) (Object) this).getPacketListener();
        if (!(listener instanceof ServerCommonPacketListenerImpl serverListener)
                || !(((AccessorServerCommonPacketListener) serverListener)
                        .flashbackNeoForgeFixed$getServer() instanceof ReplayServer)) {
            return;
        }

        String message = exception.getMessage();
        String key = message == null ? exception.getClass().getName() : message;
        if (FLASHBACK_NEOFORGE_FIXED$LOGGED_ENCODER_FAILURES.add(key)) {
            FLASHBACK_NEOFORGE_FIXED$LOGGER.warn(
                    "Dropped an unencodable payload generated by replay-server join synchronization; "
                            + "the replay connection will remain active: {}",
                    key);
        }
        ci.cancel();
    }
}
